/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.sirius.tests.sample.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class StatemachineUiModule extends AbstractStatemachineUiModule {
}
