<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sequence" nsURI="http://www.eclipse.org/sirius/diagram/sequence/2.0.0"
    nsPrefix="sequence">
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDDiagram" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//DSemanticDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticOrdering" eType="#//ordering/EventEndsOrdering"
        transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphicalOrdering" eType="#//ordering/EventEndsOrdering"
        transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceRoleSemanticOrdering"
        eType="#//ordering/InstanceRolesOrdering" transient="true" containment="true"/>
  </eClassifiers>
  <eSubpackages name="description" nsURI="http://www.eclipse.org/sirius/diagram/sequence/description/2.0.0"
      nsPrefix="description">
    <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagramDescription" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/DiagramDescription">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endsOrdering" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a Collection&lt;EObject> or an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="eventEnds" value="a List&lt;EObject> containing the semantic event ends."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceRolesOrdering"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a Collection&lt;EObject> or an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceRoleMapping" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/NodeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="EventMapping" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="DelimitedEventMapping" abstract="true"
        eSuperTypes="#//description/EventMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startingEndFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="finishingEndFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionMapping" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/NodeMapping #//description/DelimitedEventMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="StateMapping" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/NodeMapping #//description/DelimitedEventMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="EndOfLifeMapping" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/NodeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageMapping" abstract="true" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/EdgeMapping #//description/EventMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendingEndFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="receivingEndFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BasicMessageMapping" eSuperTypes="#//description/MessageMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="oblique" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnMessageMapping" eSuperTypes="#//description/MessageMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invocationMessageFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreationMessageMapping" eSuperTypes="#//description/MessageMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="DestructionMessageMapping" eSuperTypes="#//description/MessageMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageEndVariable" eSuperTypes="../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/AbstractVariable"/>
    <eClassifiers xsi:type="ecore:EClass" name="CoveredLifelinesVariable" eSuperTypes="../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/AbstractVariable"/>
    <eClassifiers xsi:type="ecore:EClass" name="FrameMapping" abstract="true" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/ContainerMapping #//description/DelimitedEventMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coveredLifelinesExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="the list of semantic EObjects representing the lifelines which are semantically covered by the frame."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="centerLabelExpression"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="the text to show in the center of the IU"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionUseMapping" eSuperTypes="#//description/FrameMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="CombinedFragmentMapping" eSuperTypes="#//description/FrameMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperandMapping" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/ContainerMapping #//description/DelimitedEventMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="ObservationPointMapping" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/NodeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionContainerMapping" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/ContainerMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="GateMapping" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/NodeMapping"/>
    <eSubpackages name="tool" nsURI="http://www.eclipse.org/sirius/diagram/sequence/description/tool/2.0.0"
        nsPrefix="tool">
      <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagramToolDescription"/>
      <eClassifiers xsi:type="ecore:EClass" name="OrderedElementCreationTool" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="startingEndPredecessor"
            eType="#//description/MessageEndVariable" containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="startingEndPredecessor"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="finishingEndPredecessor"
            eType="#//description/MessageEndVariable" containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="finishingEndPredecessor"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CoveringElementCreationTool" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="coveredLifelines" lowerBound="1"
            eType="#//description/CoveredLifelinesVariable" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceRoleCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/NodeCreationDescription #//description/tool/SequenceDiagramToolDescription">
        <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/tool/ElementVariable"
            containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="predecessor"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LifelineCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/ContainerCreationDescription #//description/tool/SequenceDiagramToolDescription"/>
      <eClassifiers xsi:type="ecore:EClass" name="MessageCreationTool" eSuperTypes="#//description/tool/SequenceDiagramToolDescription ../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/EdgeCreationDescription #//description/tool/OrderedElementCreationTool"/>
      <eClassifiers xsi:type="ecore:EClass" name="ExecutionCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/NodeCreationDescription #//description/tool/SequenceDiagramToolDescription #//description/tool/OrderedElementCreationTool"/>
      <eClassifiers xsi:type="ecore:EClass" name="StateCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/NodeCreationDescription #//description/tool/SequenceDiagramToolDescription #//description/tool/OrderedElementCreationTool"/>
      <eClassifiers xsi:type="ecore:EClass" name="InteractionUseCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/ContainerCreationDescription #//description/tool/SequenceDiagramToolDescription #//description/tool/OrderedElementCreationTool #//description/tool/CoveringElementCreationTool"/>
      <eClassifiers xsi:type="ecore:EClass" name="CombinedFragmentCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/ContainerCreationDescription #//description/tool/SequenceDiagramToolDescription #//description/tool/OrderedElementCreationTool #//description/tool/CoveringElementCreationTool"/>
      <eClassifiers xsi:type="ecore:EClass" name="OperandCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/ContainerCreationDescription #//description/tool/SequenceDiagramToolDescription #//description/tool/OrderedElementCreationTool"/>
      <eClassifiers xsi:type="ecore:EClass" name="ObservationPointCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/NodeCreationDescription #//description/tool/SequenceDiagramToolDescription #//description/tool/OrderedElementCreationTool"/>
      <eClassifiers xsi:type="ecore:EClass" name="ReorderTool" eSuperTypes="../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/tool/AbstractToolDescription #//description/tool/SequenceDiagramToolDescription">
        <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
            eType="#//description/EventMapping"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="startingEndPredecessorBefore"
            eType="#//description/MessageEndVariable" containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="startingEndPredecessorBefore"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="startingEndPredecessorAfter"
            eType="#//description/MessageEndVariable" containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="startingEndPredecessorAfter"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="finishingEndPredecessorBefore"
            eType="#//description/MessageEndVariable" containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="finishingEndPredecessorBefore"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="finishingEndPredecessorAfter"
            eType="#//description/MessageEndVariable" containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="finishingEndPredecessorAfter"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="onEventMovedOperation"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/tool/InitialOperation"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceRoleReorderTool" eSuperTypes="../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/tool/AbstractToolDescription #//description/tool/SequenceDiagramToolDescription">
        <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
            eType="#//description/InstanceRoleMapping"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="predecessorBefore"
            eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/tool/ElementVariable"
            containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="predecessorBefore"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="predecessorAfter" eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/tool/ElementVariable"
            containment="true">
          <eAnnotations source="toolVariable">
            <details key="name" value="predecessorAfter"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="instanceRoleMoved"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/tool/InitialOperation"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GateCreationTool" eSuperTypes="../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/tool/NodeCreationDescription #//description/tool/SequenceDiagramToolDescription #//description/tool/OrderedElementCreationTool"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="ordering" nsURI="http://www.eclipse.org/sirius/diagram/sequence/ordering/2.0.0"
      nsPrefix="ordering">
    <eClassifiers xsi:type="ecore:EClass" name="EventEndsOrdering">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceDiagram" eType="#//SequenceDDiagram"
          transient="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventEnds" upperBound="-1"
          eType="#//ordering/EventEnd"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EventEnd" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="semanticEnd" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleEventEnd" eSuperTypes="#//ordering/EventEnd">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="semanticEvent" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundEventEnd" eSuperTypes="#//ordering/EventEnd">
      <eOperations name="getSemanticEvents" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventEnds" lowerBound="1"
          upperBound="-1" eType="#//ordering/SingleEventEnd" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceRolesOrdering">
      <eStructuralFeatures xsi:type="ecore:EReference" name="semanticInstanceRoles"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="template" nsURI="http://www.eclipse.org/sirius/diagram/sequence/template/2.0.0"
      nsPrefix="template">
    <eClassifiers xsi:type="ecore:EClass" name="TTransformer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TAbstractMapping" eSuperTypes="#//template/TTransformer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainClass" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/TypeName">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The domain class of the mapping."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticCandidatesExpression"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="In the default case, candidates of a mapping are all EObjet owned by the semantic element of the view container. The semanticCandidatesExpression is an expression that returns the list of EObject that are candidates of the mapping instead of the candidates of the default case. The context of the expression is the semantic element of the view container."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="contentassist" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a Collection&lt;EObject> or an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="containerView" value="the parent view of potential candidates."/>
          <details key="diagram" value="the current DDiagram."/>
          <details key="viewpoint" value="(deprecated) the current DDiagram."/>
          <details key="viewPoint" value="(deprecated) the current DDiagram."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TSequenceDiagram" eSuperTypes="../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/RepresentationTemplate #//template/TTransformer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainClass" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/TypeName">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The domain class of the mapping."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endsOrdering" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a Collection&lt;EObject> or an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="eventEnds" value="a List&lt;EObject> containing the semantic event ends."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lifelineMappings" upperBound="-1"
          eType="#//template/TLifelineMapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messageMappings" upperBound="-1"
          eType="#//template/TMessageMapping" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TMessageExtremity" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TLifelineMapping" eSuperTypes="#//template/TAbstractMapping #//template/TMessageExtremity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="eolVisibleExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a boolean."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="containerView" value="the view that sould contain the potential views of the checked elements."/>
          <details key="container" value="the semantic element of $containerView."/>
          <details key="viewpoint" value="(deprecated) the current DSemanticDiagram."/>
          <details key="diagram" value="the current DSemanticDiagram."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="executionMappings" upperBound="-1"
          eType="#//template/TExecutionMapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instanceRoleStyle" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/style/NodeStyleDescription"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lifelineStyle" lowerBound="1"
          eType="#//template/TLifelineStyle" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endOfLifeStyle" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//description/style/NodeStyleDescription"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalLifeLineStyles"
          upperBound="-1" eType="#//template/TConditionalLifelineStyle" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="All conditional styles."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TLifelineStyle" eSuperTypes="#//template/TTransformer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lifelineWidthComputationExpression"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression"
          defaultValueLiteral="0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An expression computing the size of the border."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an integer."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lifelineColor" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/ColorDescription"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TConditionalLifelineStyle" eSuperTypes="#//template/TTransformer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicateExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This expression will get evaluated and if it returns true the contained style will be choosen."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a boolean."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="view" value="the current view."/>
          <details key="container" value="the semantic container."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" lowerBound="1"
          eType="#//template/TLifelineStyle" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TExecutionMapping" eSuperTypes="#//template/TAbstractMapping #//template/TMessageExtremity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startingEndFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="finishingEndFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="recursive" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="executionMappings" upperBound="-1"
          eType="#//template/TExecutionMapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" lowerBound="1"
          eType="#//template/TExecutionStyle" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalStyles" upperBound="-1"
          eType="#//template/TConditionalExecutionStyle" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TExecutionStyle" eSuperTypes="#//template/TTransformer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderSizeComputationExpression"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression"
          defaultValueLiteral="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An expression computing the size of the border."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an integer."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="borderColor" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/ColorDescription"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/ColorDescription"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TConditionalExecutionStyle" eSuperTypes="#//template/TTransformer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicateExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This expression will get evaluated and if it returns true the contained style will be choosen."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a boolean."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="view" value="the current view."/>
          <details key="container" value="the semantic container."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" lowerBound="1"
          eType="#//template/TExecutionStyle" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TMessageMapping" abstract="true" eSuperTypes="#//template/TAbstractMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendingEndFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="receivingEndFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" lowerBound="1"
          eType="#//template/TMessageStyle" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalStyle" upperBound="-1"
          eType="#//template/TConditionalMessageStyle" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TMessageStyle" eSuperTypes="#//template/TTransformer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="strokeColor" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/ColorDescription">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The color of the edge."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineStyle" eType="ecore:EEnum ../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//LineStyle">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The style of the line."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceArrow" lowerBound="1"
          eType="ecore:EEnum ../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//EdgeArrows"
          defaultValueLiteral="NoDecoration">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The source decoration."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetArrow" lowerBound="1"
          eType="ecore:EEnum ../../org.eclipse.sirius.diagram.model/model/diagram.ecore#//EdgeArrows"
          defaultValueLiteral="InputArrow">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The target decoration."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelExpression" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression"
          defaultValueLiteral="feature:name">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Expression that computes the name of a node."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="contentassist" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a string."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="diagram" value="the current DSemanticDiagram."/>
          <details key="view" value="the current view for which the label is calculated."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TConditionalMessageStyle" eSuperTypes="#//template/TTransformer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicateExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This expression will get evaluated and if it returns true the contained style will be choosen."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a boolean."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="view" value="the current view."/>
          <details key="container" value="the semantic container."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" lowerBound="1"
          eType="#//template/TMessageStyle" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TBasicMessageMapping" eSuperTypes="#//template/TSourceTargetMessageMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          upperBound="-1" eType="#//template/TMessageExtremity"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="oblique" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TSourceTargetMessageMapping" abstract="true"
        eSuperTypes="#//template/TMessageMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          upperBound="-1" eType="#//template/TMessageExtremity"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceFinderExpression"
          eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The elements that are represented by this connection."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="contentassist" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a Collection&lt;EObject> or an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="diagram" value="the current DDiagram."/>
          <details key="viewpoint" value="(deprecated) the current DDiagram."/>
          <details key="viewPoint" value="(deprecated) the current DDiagram."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The elements that are represented by this connection."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="contentassist" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="a Collection&lt;EObject> or an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables">
          <details key="diagram" value="the current DDiagram."/>
          <details key="viewpoint" value="(deprecated) the current DDiagram."/>
          <details key="viewPoint" value="(deprecated) the current DDiagram."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="useDomainElement" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TReturnMessageMapping" eSuperTypes="#//template/TMessageMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocationMapping" lowerBound="1"
          eType="#//template/TBasicMessageMapping"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invocationMessageFinderExpression"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression">
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/returnType">
          <details key="returnType" value="an EObject."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/sirius/interpreted/expression/variables"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TCreationMessageMapping" eSuperTypes="#//template/TSourceTargetMessageMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          upperBound="-1" eType="#//template/TLifelineMapping"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TDestructionMessageMapping" eSuperTypes="#//template/TSourceTargetMessageMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          upperBound="-1" eType="#//template/TLifelineMapping"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
