<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="propertiesextwidgetsreference" nsURI="http://www.eclipse.org/sirius/properties/1.0.0/ext/widgets/reference"
    nsPrefix="properties-ext-widgets-reference">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExtReferenceDescription" abstract="true"
      eSuperTypes="../../org.eclipse.sirius.properties/model/properties.ecore#//AbstractWidgetDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceNameExpression"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceOwnerExpression"
        eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onClickOperation" eType="ecore:EClass ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/tool/InitialOperation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//ExtReferenceWidgetStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalStyles" upperBound="-1"
        eType="#//ExtReferenceWidgetConditionalStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//ExtReferenceDescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtReferenceDescription" eSuperTypes="#//AbstractExtReferenceDescription ../../org.eclipse.sirius.properties/model/properties.ecore#//WidgetDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtReferenceWidgetStyle" eSuperTypes="../../org.eclipse.sirius.properties/model/properties.ecore#//WidgetStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtReferenceWidgetConditionalStyle"
      eSuperTypes="../../org.eclipse.sirius.properties/model/properties.ecore#//WidgetConditionalStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//ExtReferenceWidgetStyle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtReferenceOverrideDescription" eSuperTypes="#//AbstractExtReferenceDescription ../../org.eclipse.sirius.properties/model/properties.ecore#//AbstractOverrideDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="overrides" eType="#//ExtReferenceDescription"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterConditionalStylesFromOverriddenExtReferenceExpression"
        eType="ecore:EDataType ../../org.eclipse.sirius.model/model/viewpoint.ecore#//description/InterpretedExpression"/>
  </eClassifiers>
</ecore:EPackage>
