/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.sirius.tests.sample.xtext.scoping;

import org.eclipse.sirius.tests.sample.xtext.scoping.AbstractStatemachineScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class StatemachineScopeProvider extends AbstractStatemachineScopeProvider {
}
