/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.sirius.tests.sample.xtext.ui;

import org.eclipse.sirius.tests.sample.xtext.ui.AbstractStatemachineUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StatemachineUiModule extends AbstractStatemachineUiModule {
  public StatemachineUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
