<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contribution" nsURI="http://www.eclipse.org/sirius/description/contribution/1.0.0"
    nsPrefix="contribution">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureContribution" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFeature" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFeature" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IgnoreFeatureContribution" eSuperTypes="#//FeatureContribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetFeatureContribution" eSuperTypes="#//FeatureContribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddFeatureContribution" eSuperTypes="#//FeatureContribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveFeatureContribution" eSuperTypes="#//FeatureContribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClearFeatureContribution" eSuperTypes="#//FeatureContribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResetFeatureContribution" eSuperTypes="#//FeatureContribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectReference" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectEObjectReference" eSuperTypes="#//EObjectReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputedEObjectReference" eSuperTypes="#//EObjectReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueExpression" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//EObjectReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//EObjectReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMask" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//FeatureContribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subContributions" upperBound="-1"
        eType="#//Contribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContributionProvider" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributions" upperBound="-1"
        eType="#//Contribution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContributionPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributed" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
