/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.sirius.tests.sample.xtext;

import org.eclipse.sirius.tests.sample.xtext.StatemachineStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StatemachineStandaloneSetup extends StatemachineStandaloneSetupGenerated {
  public static void doSetup() {
    StatemachineStandaloneSetup _statemachineStandaloneSetup = new StatemachineStandaloneSetup();
    _statemachineStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
