<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="migrationmodeler" nsURI="http://www.eclipse.org/sirius/tests/sample/migrationmodeler"
    nsPrefix="migrationmodeler">
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//Representation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Container" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//Layer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicalElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNode" abstract="true" eSuperTypes="#//GraphicalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//AbstractNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeRepresentations" lowerBound="1"
        upperBound="-1" eType="#//NodeRepresentation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bordered" eSuperTypes="#//AbstractNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="borderedRepresentations"
        lowerBound="1" upperBound="-1" eType="#//BorderedRepresentation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//GraphicalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerRepresentations"
        lowerBound="1" upperBound="-1" eType="#//ContainerRepresentation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//GraphicalElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//GraphicalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeRepresentations" lowerBound="1"
        upperBound="-1" eType="#//EdgeRepresentation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//GraphicalElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//GraphicalElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRepresentation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappingId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//Layout"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinned" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeRepresentation" eSuperTypes="#//AbstractRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//GraphicalElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//GraphicalElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" upperBound="-1"
        eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStyle" eType="#//EdgeStyle"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The style of the connection."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNodeRepresentation" abstract="true"
      eSuperTypes="#//AbstractRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bordereds" upperBound="-1"
        eType="#//Bordered" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStyle" eType="#//NodeStyle"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The style of the node."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeRepresentation" eSuperTypes="#//AbstractNodeRepresentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="BorderedRepresentation" eSuperTypes="#//AbstractNodeRepresentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerRepresentation" eSuperTypes="#//AbstractRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStyle" eType="#//ContainerStyle"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The style of the container."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoSized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routingStyle" eType="#//RoutingStyle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beginLabelStyle" eType="#//BasicLabelStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerLabelStyle" eType="#//BasicLabelStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endLabelStyle" eType="#//BasicLabelStyle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoutingStyle">
    <eLiterals name="Straight"/>
    <eLiterals name="Manhattan" value="1"/>
    <eLiterals name="Tree" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LabelPosition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Position of the label."/>
    </eAnnotations>
    <eLiterals name="border">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The label is on border."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="node" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The label is on the node."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" upperBound="-1"
        eType="#//Representation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Representation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BorderedStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="borderColor" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontFormat">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The format of the font."/>
    </eAnnotations>
    <eLiterals name="normal"/>
    <eLiterals name="italic" value="1"/>
    <eLiterals name="bold" value="2"/>
    <eLiterals name="bold_italic" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeStyle" eSuperTypes="#//LabelStyle #//BorderedStyle">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Style of a node."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPosition" eType="#//LabelPosition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The position of the label :&#xD;&#xA;BORDER : The label is around the node, on the border.&#xD;&#xA;NODE : the label is in the node."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hideLabelByDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The default visibility of the label (available only if labelPosition equals BORDER).&#xA;A change of this option does not affect already existing elements."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicLabelStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelSize" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The font size."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelFormat" eType="#//FontFormat"
        defaultValueLiteral="normal">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The font format."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showIcon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True, if the icon shoud be dispayed on the element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelColor" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The path of the icon to display on the element. If unset, the icon corresponding to the semantic element will be displayed."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerStyle" eSuperTypes="#//LabelStyle #//BorderedStyle">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The style of a container."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelStyle" eSuperTypes="#//BasicLabelStyle">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The style of a label."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelAlignment" eType="#//LabelAlignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LabelAlignment">
    <eLiterals name="CENTER"/>
    <eLiterals name="LEFT" value="1"/>
    <eLiterals name="RIGHT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dot" eSuperTypes="#//NodeStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" eType="#//Color"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background color."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GaugeSection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The gauge section represents one gauge of a GaugeCompositeStyle."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The min value of the gauge."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The max value of the gauge."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The current value."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The label of the gauge."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" eType="#//Color"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background color."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foregroundColor" eType="#//Color"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The foreground color."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlatContainerStyle" eSuperTypes="#//ContainerStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundStyle" lowerBound="1"
        eType="#//BackgroundStyle">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background style."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" eType="#//Color"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background color."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foregroundColor" eType="#//Color"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The foreground color."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShapeContainerStyle" eSuperTypes="#//ContainerStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" lowerBound="1" eType="#//ContainerShape"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" lowerBound="1"
        eType="#//Color" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContainerShape">
    <eLiterals name="parallelogram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BackgroundStyle">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Style of the background of a container."/>
    </eAnnotations>
    <eLiterals name="GradientLeftToRight">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gradient style."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Liquid" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Liquid style."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GradientTopToBottom" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gradient style."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Square" eSuperTypes="#//NodeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return all nodes that have been created with the specified mapping."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The height of the square."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlignmentKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Possible alignments of gauges."/>
    </eAnnotations>
    <eLiterals name="VERTICAL" literal="VERTICAL"/>
    <eLiterals name="HORIZONTAL" value="1"/>
    <eLiterals name="SQUARE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ellipse" eSuperTypes="#//NodeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalDiameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The horizontal diameter size of the ellipse. (Semimajor axis)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalDiameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The vertical diameter of the ellipse. (Semiminor axis)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lozenge" eSuperTypes="#//NodeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The width of the lozenge."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The height of the lozenge."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BundledImageShape">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Default shapes."/>
    </eAnnotations>
    <eLiterals name="square"/>
    <eLiterals name="stroke" value="1"/>
    <eLiterals name="triangle" value="3"/>
    <eLiterals name="dot" value="4"/>
    <eLiterals name="ring" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundledImage" eSuperTypes="#//NodeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" lowerBound="1" eType="#//BundledImageShape">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The shape to use."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" lowerBound="1" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceImage" eSuperTypes="#//NodeStyle #//ContainerStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workspacePath" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The path of the image to use."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GaugeCompositeStyle" eSuperTypes="#//NodeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//AlignmentKind"
        defaultValueLiteral="SQUARE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The alignment of the gauges"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//GaugeSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//NodeStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
