name: Generate Maven SBOM

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  JAVA_VERSION: "25"
  JAVA_DISTRO: "temurin"

permissions:
  contents: read

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Java SDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Extract product version
        id: version
        shell: bash
        run: |
          VERSION="$(git describe --long HEAD)"
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Product version: $VERSION"

      - name: Generate SBOM
        env:
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn --quiet -Dmaven.test.skip.exec=true -Dxml.skip=true -Dcheckstyle.skip=true -f packaging/org.eclipse.sirius.parent/pom.xml -Psbom,headless,full,junit,swtbot-sequence,swtbot clean package

      - name: Upload SBOM
        uses: eclipse-csi/workflows/upload-sbom@20e3c63807b2bd61b7f1a9f438e5ce588c054efc # main
        with:
          sbom-file: packaging/org.eclipse.sirius.update/target/bom.json
          product-name: "Sirius Desktop"
          product-version: ${{ steps.version.outputs.PROJECT_VERSION }}
